FROM govcmslagoon/test

COPY themes/ /app/sites/default/themes/custom
COPY libraries/ /app/sites/default/libraries
COPY modules/ /app/sites/default/modules

RUN rm -Rf /app/tests/behat/features/*
COPY tests/behat/features/ /app/tests/behat/features

RUN rm -Rf /app/tests/phpunit/tests/*
COPY tests/phpunit/tests/ /app/tests/phpunit/tests
